version: "3"
services:
  app:
    build: ./server
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "./server:/go/src/app"
    container_name: app
  web:
    build: ./nginx
    ports:
      - "80:80"
    container_name: web
    depends_on:
      - app
